scp -r index.html picasso@files.mde.utc:public_html/picsous/
scp -r app/app.js picasso@files.mde.utc:public_html/picsous/app/
scp -r app/directives picasso@files.mde.utc:public_html/picsous/app/
scp -r app/services picasso@files.mde.utc:public_html/picsous/app/
scp -r app/controllers picasso@files.mde.utc:public_html/picsous/app/
scp -r bower_components picasso@files.mde.utc:public_html/picsous/
scp -r styles picasso@files.mde.utc:public_html/picsous/
scp -r views picasso@files.mde.utc:public_html/picsous/
scp -r uib picasso@files.mde.utc:public_html/picsous/
